name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: build with parcel
        run: |
          npm install
          npm run build-ghpages

      - name: deply toGitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: ./dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
